pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  all-dbs-password: 'Password12!' # Same across mysql and postgres
  all-dbs-name: 'test' # Same across mysql and postgres
  postgres-path: 'C:\Program Files\PostgreSQL\9.6'
  postgres-user: 'postgres'
  mysql-path: 'C:\Program Files\MySql\MySQL Server 5.7'
  mysql-user: 'root'

steps:
- task: NuGetToolInstaller@0

- task: PowerShell@2
  inputs: 
    targetType: 'inline'
    script: 'nuget install redis-64 -excludeversion'
  displayName: 'redis nuget'

- task: PowerShell@2
  inputs: 
    targetType: 'inline'
    script: 'redis-64\tools\redis-server.exe --service-install; redis-64\tools\redis-server.exe --service-start'
    displayName: 'redis install and run'

- task: DockerCompose@0
  inputs:
    dockerComposeFile: '.\build\docker-compose.yml' 
    action: 'Run A Specific Service' # Options: build Services, push Services, run Services, run A Specific Service, lock Services, write Service Image Digests, combine Configuration, run A Docker Compose Command
    serviceName: 'postgres' # Required when action == Run A Specific Service
  displayName: 'run postgres container'

- task: DockerCompose@0
  inputs:
    dockerComposeFile: '.\build\docker-compose.yml' 
    action: 'Run A Specific Service' # Options: build Services, push Services, run Services, run A Specific Service, lock Services, write Service Image Digests, combine Configuration, run A Docker Compose Command
    serviceName: 'mysql' # Required when action == Run A Specific Service
  displayName: 'run mysql container'